### ISSUE TITLE
[1.14.3] Conflict with Lycanites Exception caught during firing event: null

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#1]
I have a pack with over 100 mods and once I added UselessMod I started getting a crash on start up.

I made a new pack with only Lycanites and Useless Mod and it still happens.

Log- https://gist.github.com/ProsperCraft/e11d245472f4ab7de242b2054e3d38a2

[debug.log](https://github.com/TheMCBrothers/UselessMod/files/3409526/debug.log)
[latest.log](https://github.com/TheMCBrothers/UselessMod/files/3409527/latest.log)

**Comment by ProsperCraft** [comment]
https://gitlab.com/Lycanite/LycanitesMobs/issues/526

**Comment by TheMCBrothers-Manager** [comment]
This problem was solved in version 1.14.4-2.2.0
