### ISSUE TITLE
[1.14.4] Stacktraces on load NPE -  Failed to load data for block entity uselessmod:energy_cable [537/1940] java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#10]
**Describe the bug**

**Forge Version** forge-1.14.4-28.1.39
**Mod Version** UselessMod-1.14.4-2.2.4

https://gist.github.com/ProsperCraft/191e1e5329c60c935e321235ba53d6a6

**Comment by TheMCBrothers-Manager** [comment]
I have rewritten the entire energy cable code.
It still does not work 100% correctly, but it will be enough for the next update.
This bug should be fixed in 1.14.4-2.2.5
