### ISSUE TITLE
[1.14.4] Server Crash StackOverflowError: Ticking block entity

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#13]
**Describe the bug**
https://gist.github.com/ProsperCraft/4f9534a363f392c4583c65453d814928

**Forge Version** forge-1.14.4-28.1.40
**Mod Version**UselessMod-1.14.4-2.2.4

**Comment by TheMCBrothers-Manager** [comment]
This will be fixed in 1.14.4-2.2.5.
Release Date: today
