### ISSUE TITLE
[1.14.4] Energy cables don't connect to solar panels.

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#15]
**Describe the bug**
After the 2.2.5 update energy cables no longer transfer power, or connect to Engineer's decor solar panels.

**Forge Version**forge-1.14.4-28.1.44
**Mod Version**UselessMod-1.14.4-2.2.5

![2019-10-12_19 32 14](https://user-images.githubusercontent.com/4427684/66709742-c704d180-ed27-11e9-8f04-a3f0508d96a4.png)
![2019-10-12_19 34 50](https://user-images.githubusercontent.com/4427684/66709743-c704d180-ed27-11e9-8d42-fc3f8626f7db.png)
![2019-10-12_19 34 54](https://user-images.githubusercontent.com/4427684/66709744-c704d180-ed27-11e9-951f-fcc68cd2cc18.png)

**Comment by TheMCBrothers-Manager** [comment]
They don't connect, but they should transfer energy.
If not, this will be fixed in 1.14.4-2.2.6
