### ISSUE TITLE
[1.14.4] Client crash when placing Silent wire against useless energy cable.

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#17]
**Describe the bug**
https://github.com/SilentChaos512/Silents-Mechanisms/issues/36

Forge Versionforge-1.14.4-28.1.47.jar
Mod Version UselessMod-1.14.4-2.2.5.jar

**Comment by ProsperCraft** [comment]
https://paste.fedoraproject.org/paste/ybizS-kk4au9jED0Q~EM9g

**Comment by ProsperCraft** [comment]
https://paste.fedoraproject.org/paste/6DOLksTU6eFjsMUUASQCcA

**Comment by TheMCBrothers-Manager** [comment]
This problem should no longer occur because the cables no longer connect with each other
