### ISSUE TITLE
[1.14.4] issue title nightconfig error

### ISSUE THREAD

**Issue by SDUBZ** [TheMCBrothers/UselessMod#18]
**Describe the bug**
crashes on load up nightconfig error

**Forge Version** 28.1.92
**Mod Version** 2.2.5
logs:
http://puu.sh/EHMAg/67db5997d2.log
http://puu.sh/EHMAb/c180185543.log

**Comment by SDUBZ** [comment]
@TheMCBrothers

**Comment by TheMCBrothers-Manager** [comment]
Thank you for reporting this issue!
I will try to fix this bug
