### ISSUE TITLE
[1.14.4] Client crash on load- ava.lang.IllegalAccessError: no such constructor: tk.themcbros.uselessmod.compat.top.TheOneProbeSupport.<init>()v

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#19]
**Describe the bug**
Client crash after updating the mods in my The Adventures of Halk pack.

Stacktrace-
https://gist.github.com/ProsperCraft/711ba7b6ca9d00a5c05ba9853d50b32c

Full log- 
https://gist.github.com/ProsperCraft/7a64803d3b0330b62116af44e226bf1b

**Forge Version**  1.14.4 - 28.1.104

**Mod Version**  UselessMod-1.14.4-2.2.6

**Comment by FuuNoKamiOka** [comment]
I also experienced this crash. In self-made pack.

Forge Version: 1.14.4 - 28.1.104
Mod Version: 1.14.4-2.2.6

**Comment by TheMCBrothers-Manager** [comment]
Thanks for reporting this issue.
Hopefully this will be fixed in the next version
