### ISSUE TITLE
[1.14.4] Client crash when opening the crusher on a server.

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#2]
When you open the crusher interface on a dedicated server your client crashes-
https://gist.github.com/ProsperCraft/e4ab40f2503f783b0dbf3592f0c6b3f1

It doesn't happen in single player.

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

UselessMod-1.14.4-2.2.0
forge-1.14.4-28.0.21

**Comment by mdylantk** [comment]
It only happen on a server with quite a bit of mods(it do not always happen and almost seem random). I can not reproduce it on a server with this as the only mod.

**Comment by ProsperCraft** [comment]
Reproduced here -  https://gist.github.com/ProsperCraft/4e23a943b23e3c863373ccb90505e744

With UselessMod-1.14.4-2.2.1
