### ISSUE TITLE
[1.14.4] Server crash when placing a hopper against the left side of a glowstone generator.

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#3]
If you place a hopper against the glowstone generator and put glowstone in the hopper the dedicated server crashes

https://gist.github.com/ProsperCraft/f39c5a3204d24b179d2d4ff3ffa7c8b4

Then each time the player logs in it crashes again-

https://gist.github.com/ProsperCraft/0885c062ab6b581a74790d78e02e515a

This was reproduced in single player as well-

https://gist.github.com/ProsperCraft/0885c062ab6b581a74790d78e02e515a

1.14.4 modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Hoppers were tested with glowstone to a chest with no crash.

**Comment by ProsperCraft** [comment]
Reproduced in single player with only useless mod -

https://gist.github.com/ProsperCraft/44271218cfee18ffea071a7aa61d1176

**Comment by TheMCBrothers-Manager** [comment]
This issue will be fixed in the next release
