### ISSUE TITLE
[Forge 1.20.1] Crash on going into Creative on server

### ISSUE THREAD

**Issue by Gamerbolts** [TheMCBrothers/UselessMod#31]
**Describe the bug**
I added your mod to my altered ATM9 Modpack. I ran a server and client, Joined and everything was fine, then I switched into creative mod and crashed.

**To Reproduce**
Unfortunately because it is a modified version of ATM9 you would need to download that and then install the 200 mods I added...

**Expected behavior**
Go into creative mode

**Screenshots**
n/a

**Runtime environment (please complete the following information):**
 - Minecraft Version: [1.20.1]
 - Forge Version [47.2.16]
 - Mod Version [7.2.0]

**Additional context**
Here is my crashlog
[crash-2023-12-28_11.56.47-client.txt](https://github.com/TheMCBrothers/Useless-Mod/files/13788490/crash-2023-12-28_11.56.47-client.txt)
And my normal log
[latest.log](https://github.com/TheMCBrothers/Useless-Mod/files/13788494/latest.log)

**Comment by TheMCLoveMan** [comment]
Thank you very much for reporting this bug! This should be resolved in version 7.2.1 for Minecraft 1.20.1
