### ISSUE TITLE
[1.14.4] Crashing vanilla recipe book

### ISSUE THREAD

**Issue by Knito58** [TheMCBrothers/UselessMod#5]
MC 1.14.4 Forge 28.0.41 UselessMod-1.14.4-2.2.2

JEI does not work atm so I thought "vanilla has a recipe book, too". But when clicking the book the game crashes.

https://pastebin.com/25mHSBb9

`
java.lang.AbstractMethodError: Method tk/themcbros/uselessmod/recipes/CompressorRecipe.func_194133_a(II)Z is abstract
	at tk.themcbros.uselessmod.recipes.CompressorRecipe.func_194133_a(CompressorRecipe.java) ~[?:1.14.4-2.2.2] {}
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:37) ~[?:?] {}
...`

**Comment by ProsperCraft** [comment]
Jei Fixed btw, it is updated to forge .45

**Comment by TheMCBrothers-Manager** [comment]
This issue will be fixed in the next version.
It crashes because of missing methods, which aren't needed in earlier versions of Forge
And JEI is updated. Use that. It's better anyway
