### ISSUE TITLE
[1.14.4] Client config fails to generate com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: 

### ISSUE THREAD

**Issue by ProsperCraft** [TheMCBrothers/UselessMod#8]
Stacktrace on load
https://gist.github.com/ProsperCraft/8c5554894c689353eff904a2cd03b7a7

I wiped the empty config file, and it made a new empty config file on load.

Full log -
https://gist.github.com/ProsperCraft/b3c177e362ce1c011beedc203a69332a

	UselessMod-1.14.4-2.2.3.jar
Forge .45

**Comment by TheMCBrothers-Manager** [comment]
I hope this bug has been fixed by Forge as there is a recommended version
So I will close this issue
